### ISSUE TITLE
Please use the latest version of guava 32.1.3.jre

### ISSUE THREAD

**Issue by merks** [eclipse-cdo/cdo#31]
https://github.com/eclipse-simrel/simrel.build/issues/80

**Comment by estepper** [comment]
Hi Ed,

CDO doesn't use Guava and never did. Probably a transitive effect of depending on EMF Compare.
I don't think that I can do anything, right?

**Comment by merks** [comment]
It appears that you just don't recognize that you use Guava.  Consider where these dependencies come from:

https://github.com/eclipse-cdo/cdo/blob/b565adce15c49baafb3edb251e3beb19186405a8/plugins/org.eclipse.emf.cdo.compare/META-INF/MANIFEST.MF#L17-L20

From this in your target platform:

https://github.com/eclipse-cdo/cdo/blob/b565adce15c49baafb3edb251e3beb19186405a8/releng/org.eclipse.emf.cdo.releng.parent/tp/org.eclipse.emf.cdo.releng.tp.target#L9

If you look on the train for that package, this is where that package comes from:

![image](https://github.com/eclipse-cdo/cdo/assets/208716/eca0eca4-d021-4a56-b16c-febb31d27afc)

So yes you are using guava and you are excluding 32.1.3 from your range so you can definitely do something, minimally to expand your range to `33.0.0)`.

**Comment by estepper** [comment]
I see, how odd!

I'll look at it and fix it tomorrow when I'm back home...

**Comment by estepper** [comment]
I've increased the upper bound to 34.0.0.
