### ISSUE TITLE
Provide Ant tasks to perform CDO operations

### ISSUE THREAD

**Issue by jgsuess** [eclipse-cdo/cdo#45]
I have created a headless runtime for MDE within DevOps (see [here for blueprint](https://link.springer.com/article/10.1007/s10270-022-01003-2) or [MDE-Devops](https://gitlab.com/committed-consulting/mde-devops/)).

However, one of the weak spots of the approach is that model versioning is not file versioning. CDO fills that gap.

But CDO cannot be operated from ant, so it cannot be used for this purpose.

Hence it would be great to have ant tasks that replicate the functionality of GUI.

**Comment by estepper** [comment]
CDO can be operated stand-alone (i.e., without OSGi running), both client and server, so I would expect that it can also be operated from Ant.

The functionality of the CDO UI is extensive, so it would be good to specify the set of CDO operations more precisely.

Are you planning to contribute your proposed improvement(s) to CDO?

**Comment by jgsuess** [comment]
@ specify the set of CDO operations more precisely.
I was thinking of basic operations like establishing a checkout and commit. Epsilon has a driver that does this implicitly, but it hides a lot of the concepts.

@ Are you planning to contribute your proposed improvement(s) to CDO?
Yes. I would think users would expect to find them as part of the CDO package, rather than separately.

**Comment by estepper** [comment]
> @ Are you planning to contribute your proposed improvement(s) to CDO? 
> Yes. I would think users would expect to find them as part of the CDO package, rather than separately.

That's good because I definitely won't have resources to work on this. Of course I'll be able to help with knowledge ;-)

Note that the `org.eclipse.emf.cdo.migrator` plugin already provides some Ant tasks and builds/packages them as part of the workspace build...

**Comment by estepper** [comment]
Have you made progress already?

**Comment by estepper** [comment]
As I haven't heard from you I close this as not planned for now. Please reopen when there's something.
