### ISSUE TITLE
[GMF Notation] eIsSet() methods should use the getXXXGen() getters to avoid a NPE

### ISSUE THREAD

**Issue by vsennedot** [eclipse-cdo/cdo#53]
Some classes of GMF Notation that are migrated for CDO can throw a NPE during the eIsSet() method because the behavior is not exactly the same as the one before the migration.

For example, in SortingStyleImpl:
```
case NotationPackage.SORTING_STYLE__SORTING_KEYS:
    return SORTING_KEYS_EDEFAULT == null ? sortingKeys != null : !SORTING_KEYS_EDEFAULT.equals(sortingKeys); 
```

is replaced by:
```
case NotationPackage.SORTING_STYLE__SORTING_KEYS:
    return SORTING_KEYS_EDEFAULT == null ? getSortingKeys() != null : !SORTING_KEYS_EDEFAULT.equals(getSortingKeys());
```

But getSortingKeys() is not exactly like sortingKeys as it returns an unmodifiable map which can throw a NPE if the original map is null.

The case with a null value can occurs if the GMF object was not yet migrated to CDO and used with a CDOLegacyAdapter in a repository. The default values don't seem to be stored with a CDOLegacyAdapter and stay as null in the repository.
When loading this repository with GMF Notation metamodel migrated to CDO, the stored value is still null.

**Comment by estepper** [comment]
Hi Vincent, Sorry for the late reply. I think I have a vague idea what you mean, but not enough to apply concrete changes. Is it possible that you provide a pull request?

**Comment by vsennedot** [comment]
I made the pull request, modifying the migrate.ant too.

But when try to generate the model code, it appears that the last version of the CDO migrator doesn't work. The `Messages` class in `org.eclipse.emf.cdo.migrator` has been moved, but the `BUNDLE_NAME` constant has not been updated.

**Comment by estepper** [comment]
Hi Vincent, thank you very much! I've cherry-picked your commit locally to avoid pushing your merge commit. I've also bumbep the plugin version and pushed everthing with your author ID. Thank you again ;-)

**Comment by estepper** [comment]
Hi Vincent, thank you very much! I've cherry-picked your commit locally to avoid pushing your merge commit. I've also bumbep the plugin version and pushed everthing with your author ID. Thank you again ;-)

**Comment by vsennedot** [comment]
Hi Eike, thank you! And sorry for the merge commit, I wasn't very comfortable yet with fork and pull request on GitHub, but the next time I will know what to do!

**Comment by estepper** [comment]
No worries, my period of uncomfortable feelings is not so long ago ;-)
