### ISSUE TITLE
Potential compatibility issue with the upcoming OCL version

### ISSUE THREAD

**Issue by pcdavid** [eclipse-cdo/cdo#62]
OCL has recently introduced [a change](https://git.eclipse.org/c/ocl/org.eclipse.ocl.git/diff/plugins/org.eclipse.ocl/src/org/eclipse/ocl/OCL.java?id=b13265da499a26dfdb8c1bfdd39de9ddcd2d89d0) which removes the `OCL.newInstance()` static methods (see https://www.eclipse.org/lists/cross-project-issues-dev/msg19930.html and https://bugs.eclipse.org/bugs/show_bug.cgi?id=416470#c16).

I think CDO is impacted by the change [here](https://github.com/eclipse-cdo/cdo/blob/master/plugins/org.eclipse.emf.cdo.server.ocl/src/org/eclipse/emf/cdo/server/ocl/OCLQueryHandler.java#L209).

**Comment by pcdavid** [comment]
FWIW I have a (quite ugly) workaround for EMF Validation [here](https://github.com/eclipse-emfservices/emf-validation/pull/30). If you find a better way to fix this while still being compatible with earlier OCL versions I'd be glad to hear it.

**Comment by estepper** [comment]
Please note that I'm going to replace the reflective call of the **new** OCL method by a regular call once Ed. W. has provided us with a build of his new code.

**Comment by estepper** [comment]
Reopening as a reminder...

**Comment by estepper** [comment]
Finally fixed by https://github.com/eclipse-cdo/cdo/commit/8f9eee9cd96bae279134e339889638841ad674bf#diff-31940f4df08b534805a82bc49d48f8db7a410b52720984d0b5ec08a1f8524761
