### ISSUE TITLE
Signal exception logging should be disabled by default

### ISSUE THREAD

**Issue by mPorhel** [eclipse-cdo/cdo#71]
Behavior introduced in https://bugs.eclipse.org/bugs/show_bug.cgi?id=536332 for CDO 4.10.

I created this Bugzilla 536332 after spending time to identify an issue even in debug with traced.

When moving from CDO 4.7 to CDO 4.22, we found that the chosen approach to always log but allows to disable the log with addition of -Dorg.eclipse.net4j.signal.Signal.disableLogExceptions=true in all products might not be the good choice.

We propose to replace the default value in org.eclipse.net4j.signal.Signal by changing the initialization of the corresponding field:
```
private static final boolean DISABLE_LOG_EXCEPTIONS = OMPlatform.INSTANCE.isProperty("org.eclipse.net4j.signal.Signal.disableLogExceptions", true);
```

**Comment by estepper** [comment]
> [...] might not be the good choice.

Can you elaborate a bit on why this might not be a good choice?

**Comment by mPorhel** [comment]
Initial issue was raised on CDO 4.7 in 2018, and corrected in CDO 4.10.

The initial Eclipse bugzilla was indeed  about giving the possibility to add more debug info without having to put the traces on.

By default with the current implementation and values, a user might have unwanted logs or noise with a CDO based product having the same behavior with CDO 4.7 et CDO 4.XX with x >= 4.10.  To avoid that product builders can add the -Dorg.eclipse.net4j.signal.Signal.disableLogExceptions=true  in their .product file or default .ini file, or ask user to add this when installing some CDO based plugins in their product. 
The idea of the proposed change is to  have no logs by default but the possibility to have them.

The current implementation does the following 
```
     catch (Exception ex)
     {
      if (DISABLE_LOG_EXCEPTIONS)
      {
        if (TRACER.isEnabled())
        {
          TRACER.trace("Exception in signal", ex); //$NON-NLS-1$
        }
      }
      else
       {
        OM.LOG.error(ex);
       }
```
with DISABLED_LOG_EXCEPTION set to false  by default.

We propose to switch DISABLED_LOG_EXCEPTION to true and let users enable the TRACER option or put the -Dorg.eclipse.net4j.signal.Signal.disableLogExceptions=false to have more logs when needed.

**Comment by estepper** [comment]
Ok, I understand what you mean. But I'm against the paradigm shift you're proposing. I believe that people, in case of problems, want to see them in the log. And when they have enough of that, they have a means to reduce the output. Please note that you can already take full control over what's logged or not, and how:

    OMPlatform.INSTANCE.removeLogHandler(EclipseLoggingBridge.INSTANCE);
    OMPlatform.INSTANCE.removeLogHandler(PrintLogHandler.CONSOLE);
    OMPlatform.INSTANCE.addLogHandler((logger, level, msg, ex) -> { ... });

But without further arguments for your proposal I feel inclined to close this as not planned.

**Comment by estepper** [comment]
I've added the new product group "org.eclipse.net4j.util.exceptionHandlers" to which you can contribute your custom exception handler factories. When an exception occurs, a handler factory is first looked up with the bundle name as factory type, then with factory type `null`. If no factory is found, the normal logging occurs.
