### ISSUE TITLE
javax.annotation is missing from target plaform

### ISSUE THREAD

**Issue by claesrosell** [eclipse-cdo/cdo#76]
```
[ERROR] Failed to resolve target definition file:/home/jenkins/agent/workspace/emf-cdo-build_PR-75/git/releng/org.eclipse.emf.cdo.releng.parent/tp/org.eclipse.emf.cdo.releng.tp.target: Could not find "javax.annotation/0.0.0" in the repositories of the current location
```
It is referenced by org.eclipse.emf.cdo.compare, via the `additional.bundles` directive in `build.properties` but is not used explicitly.
Should jakarta.annotation be used instead, should javax.annotation be added to the platform or should it be removed all togheter?

**Comment by merks** [comment]
FYI, I tried removing it and that built fine.   The problem with jakarta.annotation-api is there are two versions and only the 1.x version has javax names.  But I just don't understand the purpose of this in the build.properties.  It feels like noise.

**Comment by merks** [comment]
I assume this is fixed by.

https://github.com/eclipse-cdo/cdo/commit/8f9eee9cd96bae279134e339889638841ad674bf

**Comment by estepper** [comment]
Sorry, saw this issue too late. But it's fixed, as Ed said ;-)
