### ISSUE TITLE
Issues in UML2 cdo-ification scripts

### ISSUE THREAD

**Issue by SebastienRevol** [eclipse-cdo/cdo#77]
Latest updates of [UML2 metamodel](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582622)  require to re-generate a cdo version of this metamodel.
I encountered 2 issues in the process :

1. The execution of the  ant migration script fails due to a small refactoring issue in class /org.eclipse.emf.cdo.migrator/src/org/eclipse/emf/cdo/internal/migrator/messages/Messages.java where BUNDLE_NAME has not been updated in commit  #12 

2. The updated UML2 metamodel code of org.eclipse.uml2.uml.internal.impl.ElementImpl refers now to the `eFlags` class member inherited from org.eclipse.emf.ecore.impl.EModelElementImpl. This attribute is unfortunately not present in the cdo-ified version of EModelElementImpl (org.eclipse.emf.cdo.ecore.impl.EModelElementImpl).

**Comment by estepper** [comment]
Hi Séb, [PR78 ](https://github.com/eclipse-cdo/cdo/pull/78) is merged. Do we need to keep this isssue open?

**Comment by SebastienRevol** [comment]
Hello Eike, no it can be closed thanks! 
Regarding eFlags access in the cdo-ified UML version, I found out in its migrate.ant script how you previously addressed this issue in a similar case and managed to use the same approach. I pushed the updated code in [this merged request](https://gitlab.eclipse.org/eclipse/papyrus/org.eclipse.papyrus-cdo/-/merge_requests/2).
