### ISSUE TITLE
Issue during call to LMResourceSetConfigurer.CheckoutResult.reconfigure()

### ISSUE THREAD

**Issue by SebastienRevol** [eclipse-cdo/cdo#88]
In the context of LM Module checkout, if a new dependency is added to another Module through the module.md file, a call to `LMResourceSetConfigurer.CheckoutResult.reconfigure() `is triggered, causing the opening of a new view in the viewSet for the new dependency.

However, this new view opening is triggering a new execution of the complete ResourceSet configuration mechanism for this new view, ending by replacing the existing CheckoutResult by a new StandaloneResult in the original resourceSet, and containing only the dependencies introduced by the new view.  

It seems that a call to `byPassConfigure(true)` before calling `addDependencyView(module)`  in `CheckoutResult.reconfigure()`can fix the problem:  it makes sense to stop nested view configurations when the view is explicitely opened by the view configurer...
I even wonder if the "bypass" call could be directly included in the following method: `org.eclipse.emf.cdo.lm.internal.client.LMResourceSetConfigurer.Result.openDependencyView(ISystemDescriptor, AssemblyModule, ResourceSet)`

The step to reproduce the issue is simple : create 3 modules : A, B an C, with a dependency from A to B. Then add a new dependency from A to C and update the checkout of A. The resourceSet configuration result of this checkout becomes incorrect.

**Comment by estepper** [comment]
Thanks for the detailed analysis! I'll have a look now...

**Comment by estepper** [comment]
The issue is already reproducible with just modules A and B. C is not needed.

**Comment by SebastienRevol** [comment]
Thanks a lot for your light speed answer Eike ! I confirm it works fine now!!
